### ISSUE TITLE
Monitor an application from Browser

### ISSUE THREAD

**Issue by adrixpho** [lorenwest/node-monitor#23]
Hi lorenwest, I have N client applications that I need to monitor, all of them in different machines and one application as monitor server. When I try to monitor a client application from the browser using dist library I can't do a connection, I've inserted the script:

```
<script src="path/to/monitor/dist/monitor-all.js"></script>

var monitoProcess = new Monitor({
        probeClass: 'Process',
        hostName: ' IPClientApplication '
    });

monitoProcess.connect(function(error) {
        if (error) {
            console.log('Error connecting with the process probe: ', error);
        }
    });
 monitoProcess.on('connect', function(){
        console.log("Connected!");
    });
    monitoProcess.on('change', function()
    {
        var freemem = monitoProcess.get('freemem');
        console.log("Free memory: %d", freemem);
    });
```

But I don't get the connection to ProbeClass:'Process', however, if I do the same connection but from server side, I get that connection. What can I be doing wrong? By the way, I have in my client applications the property "allowExternalConnections" to true. Do you have an example how to use dashboard components individually in a browser?

Thanks!

**Comment by lorenwest** [comment]
Hi Adrian,

Browsers have a different security model than servers - they can only directly connect with processes on the same host as the one serving the page.

The way around this issue is to configure your monitor server as a gateway.  By default, the browser client will try to connect directly to the host, and if it fails it uses the gateway server.

In your monitor server, instead of doing this:

```
var Monitor = require('monitor');
Monitor.start();
```

Try this:

```
var Monitor = require('monitor');
var server = new Monitor.Server({gateway:true});
server.start();
```

The monitor-dashboard project has the same issue, and that's how it was resolved. 

Hope that helps,
-Loren

**Comment by lorenwest** [comment]
The example I have is the monitor-dashboard project.  You can see this gateway code in the lib/js/Server.js file around line 360 of the monitor-dashboard project.
